# Site settings
title: Beautiful Speeches
email: rudolphben@gmail.com
description: "Some of the world's best speeches are hidden away on some of the most unappealing websites. This sites aims to allow great speeches to be great, unhindered by ads and unpleasing color schemes."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: _benrudolph
github_username:  benrudolph

# Build settings
markdown: redcarpet
permalink: pretty
