# Site settings
title: Beautiful Speeches
email: rudolphben@gmail.com
description: "Speeches are some of the most beautiful works of art that humans have made. Beautiful Speeches aims to consolidate the greatest speeches into one site. Beyond collecting speeches, Beautiful Speeches endeavors to create a clean interface so that each word resonates on the page."
baseurl: /beautifulspeeches
url: "http://yourdomain.com"
twitter_username:
github_username:

# Build settings
markdown: redcarpet
permalink: pretty
